<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net10.0;net8.0;netstandard2.1</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <!-- NuGet Packaging -->
    <PackageId>Zmij</PackageId>
    <PackageTags>dtoa;decimal;conversion</PackageTags>
    <Description>C# port of Zmij, an extremely fast double-to-string conversion algorithm.</Description>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="README.md" />
    <EmbeddedResource Include="..\..\LICENSE" />
  </ItemGroup>
</Project>
